Generalized quadrature rules
Functions
gint grule_bgr (gdouble *x, gdouble *w, gqr_parameter_t *p)
gint gqr_rule_bgr_check (gqr_rule_t *rule, gqr_parameter_t *p, gint *imax, gdouble *emax, gboolean analytic, FILE *output)
Detailed Description
Function Documentation
gqr_rule_bgr_check()
gint gqr_rule_bgr_check (gqr_rule_t * rule, gqr_parameter_t * p, gint * imax, gdouble * emax, gboolean analytic, FILE * output)
Estimate error in generalized quadrature rules by integrating basis functions and checking against evaluation using quadrature rules.
Parameters
rule quadrature rule to check;
p parameters used to generate basis functions;
imax on exit, index of basis function with greatest error in integral;
emax on exit, greatest error in integral evaluation;
analytic reserved for future use;
output if not NULL, file stream to write diagnostic information and error estimates.
Returns
0 on success.
References gqr_rule_alloc(), gqr_rule_scale(), and gqr_rule_select().
grule_bgr()
gint grule_bgr (gdouble * x, gdouble * w, gqr_parameter_t * p)
Generate a generalized quadrature rule using the method of Bremer, Gimbutas, and Rokhlin, 2010, `A nonlinear optimization procedure for generalized Gaussian quadratures', https://dx.doi.org/10.1137/080737046
Parameters
x on output contains nodes of quadrature rule;
w on output contains weights of quadrature rule;
p parameters of basis functions of quadrature, including a pointer to the gqr_adapt_func_t which evaluates the functions.
Returns
number of nodes in rule.
References gqr_rule_alloc(), and gqr_rule_select().
Referenced by gqr_rule_select().