Evaluation of finite part integrals
Functions
gdouble gqr_finite_part (gdouble a, gdouble b, gdouble y, gdouble g)
gdouble gqr_finite_part_integral (gqr_func_t f, gpointer data, gdouble y, gdouble gm, gdouble a, gdouble b, gqr_rule_t *g)
gdouble gqr_finite_part_1mt_n (gint n, gint m)
gdouble gqr_legendre_dPdx (gdouble x, gint n, gint m)
gdouble gqr_finite_part_Pn1 (gint n, gint m)
gdouble gqr_finite_part_tn_log (gdouble x, gint n)
Detailed Description
Function Documentation
gqr_finite_part()
gdouble gqr_finite_part (gdouble a, gdouble b, gdouble y, gdouble g)
Compute the finite part integral $\mathrm{FP}\int_{a}^{b}1/(y-x)^{\gamma}\,\mathrm{d}x$ using the method of Brandao, M. P., 1987, `Improper integrals in theoretical aerodynamics: The problem revisited', AIAA Journal, 25(9):1258--1260.
Parameters
a lower limit of integration;
b upper limit of integration;
y location of singularity;
g order of singularity, $\gamma$.
Returns
finite part of $\int_{a}^{b}1/(y-x)^{\gamma}\,\mathrm{d}x$.
Referenced by gqr_finite_part_integral().
gqr_finite_part_1mt_n()
gdouble gqr_finite_part_1mt_n (gint n, gint m)
Return the finite part of $\int_{-1}^{1}(1-t)^n/(1+t)^m\,\mathrm{d}t$.
Parameters
n exponent of $(1-t)$;
m exponent of $(1+t)$;
Returns
finite part of integral.
Referenced by gqr_finite_part_Pn1().
gqr_finite_part_integral()
gdouble gqr_finite_part_integral (gqr_func_t f, gpointer data, gdouble y, gdouble gm, gdouble a, gdouble b, gqr_rule_t * g)
Compute the finite part integral $FP\int_{a}^{b}f(x)/(y-x)^{\gamma}\,\mathrm{d}x$ using a Gaussian quadrature for the regular integral. The method is that of Brandao, M. P., 1987, `Improper integrals in theoretical aerodynamics: The problem revisited', AIAA Journal, 25(9):1258--1260.
Parameters
f a gqr_func_t which returns the $j$th derivative of the function;
data data to pass to f;
y position of the singularity;
gm strength (exponent) of the singularity;
a lower limit of integration;
b upper limit of integration;
g Gaussian quadrature rule for the regular integral.
Returns
the finite part of $\int_{a}^{b}f(x)/(y-x)^{\gamma}\,\mathrm{d}x$.
References gqr_finite_part(), and gqr_rule_scale().
gqr_finite_part_Pn1()
gdouble gqr_finite_part_Pn1 (gint n, gint m)
Compute the finite part of $\int_{-1}^{1}P_{n}(x)/(1+t)^{m}\,\mathrm{d}x$.
Parameters
n order of Legendre polynomial;
m order of singularity.
Returns
$\int_{-1}^{1}P_{n}(x)/(1+t)^{m}\,\mathrm{d}x$.
References gqr_finite_part_1mt_n().
gqr_finite_part_tn_log()
gdouble gqr_finite_part_tn_log (gdouble x, gint n)
Return the value of $\int_{-1}^{1}t^{n}\log|x-t|\,\mathrm{d}t$.
@param n power of $t$; @param x position of singularity.
@return value of integral.
gqr_legendre_dPdx()
gdouble gqr_legendre_dPdx (gdouble x, gint n, gint m)
Compute the $m$th derivative of the $n$th Legendre polynomial $P_{n}(x)$ by direct evaluation (i.e. without using the recursion relation).
Parameters
x $x$;
n order of Legendre polynomial;
m order of derivative.
Returns
$P_{n}^{(m)}(x)$.