GQR quadrature rules
Typedefs
typedef struct _gqr_parameter_t gqr_parameter_t
typedef struct _gqr_rule_t gqr_rule_t
typedef gdouble(* gqr_func_t) (gdouble t, gint i, gpointer data)
typedef gdouble(* gqr_adapt_func_t) (gdouble t, gint i, gqr_parameter_t *p)
Enumerations
enum gqr_t {
 GQR_GAUSS_LEGENDRE = 1
, GQR_GAUSS_CHEBYSHEV_1 = 2
, GQR_GAUSS_CHEBYSHEV_2 = 3
, GQR_GAUSS_HERMITE = 4
,
 GQR_GAUSS_LAGUERRE = 5
, GQR_GAUSS_JACOBI = 6
, GQR_GAUSS_LOGARITHMIC = 1 << 8
, GQR_GAUSS_SINGULAR = 1 << 9
,
 GQR_GAUSS_HYPERSINGULAR = 1 << 10
, GQR_GAUSS_MULTISINGULAR = 1 << 11
, GQR_GAUSS_GENERALIZED = 1 << 12
 }
Functions
 gqr_rule_t * gqr_rule_alloc (gint n)
 gqr_rule_t * gqr_rule_realloc (gqr_rule_t *g, gint n)
gint gqr_rule_free (gqr_rule_t *g)
gint gqr_rule_write (gqr_rule_t *g, FILE *f)
gint gqr_rule_select (gqr_rule_t *g, gqr_t type, gint n, gqr_parameter_t *p)
gint gqr_rule_scale (gqr_rule_t *g, gdouble a, gdouble b, gdouble *xbar, gdouble *dx)
gchar * gqr_rule_name (gqr_t type)
 gqr_t gqr_rule_from_name (gchar *str, gqr_parameter_t *p)
gpointer gqr_pointer_parse (gchar *str)
gint gqr_pointers_list (FILE *output, gboolean verbose)
Detailed Description
The GQR library computes Gaussian and Gaussian-type quadrature rules including some which handle singular integrands. A simple complete example of a code which integrates a function is: example.c.
The functions described here are used to generate the quadrature rules and do basic operations such as reading them from and writing them to a file.
Typedef Documentation
gqr_adapt_func_t
gqr_adapt_func_t
A type for evaluating functions to be used in adaptive discretizations. Optionally, if i is negative, the function call should be interpreted as a request for the integral of the function between limits defined in the first two floating point entries in the parameter list p, with the function index taken as -(i+1).
Parameters
t evaluation point;
i the index of the function to be evaluated;
p parameter list to be passed to the function.
Returns
value of the function $f_i(t)$, or the integral of $f_{-i-1}(t)$ if $i<0$.
gqr_func_t
gqr_func_t
A type for evaluating integrands and their derivatives.
Parameters
t evaluation point;
i the order of derivative to be evaluated;
data user data to be passed to the function.
Returns
value of the $i$th derivative of the function at $t$.
gqr_parameter_t
 gqr_parameter_t
A data structure containing parameters for quadrature rules which require them.
gqr_rule_t
 gqr_rule_t
Data structure containing the nodes and weights of a quadrature rule. The rule is allocated using gqr_rule_alloc and initialized using gqr_rule_select. To transform the range of integration use gqr_rule_scale.
Enumeration Type Documentation
gqr_t
enum gqr_t
A type defining the quadrature rules available. A quadrature rule is defined as a basic type possibly combined with a singularity. For example GQR_GAUSS_LEGENDRE | GQR_GAUSS_HYPERSINGULAR specifies a Gauss-Legendre rule which handles singularities up to and including second order. Note that not all of these rules are implemented or going to be implemented. GQR will return an error message if you try to use an unimplemented rule.
Function Documentation
gqr_pointer_parse()
gpointer gqr_pointer_parse (gchar * str)
Parse a string which refers to a pointer. The main purpose of this function is to give user access to built-in functions for the generation of generalized quadratures.
Parameters
str a string to be parsed.
Returns
a pointer to the data referred to by str, or NULL.
gqr_pointers_list()
gint gqr_pointers_list (FILE * output, gboolean verbose)
List the built-in pointers recognized by gqr_pointer_parse
Parameters
output file stream to write to;
verbose if TRUE, write detailed information about the built-in data.
Returns
0 on success.
gqr_rule_alloc()
 gqr_rule_t * gqr_rule_alloc (gint n)
Allocate a Gaussian quadrature rule.
Parameters
n maximum length of rule (number of abscissae and weights).
Returns
newly allocated rule.
Referenced by gqr_rule_bgr_check(), gqr_rule_realloc(), and grule_bgr().
gqr_rule_free()
gint gqr_rule_free (gqr_rule_t * g)
Free all memory associated with a Gaussian quadrature rule.
Parameters
g rule to be freed.
Returns
0 on success.
gqr_rule_from_name()
 gqr_t gqr_rule_from_name (gchar * str, gqr_parameter_t * p)
Parse a string description of a GQR rule, returning a gqr_t description, intended for use in parsing command line options.
Parameters
str a string containing a description of a GQR rule, e.g. `GQR_GAUSS_LEGENDRE | GQR_GAUSS_LOGARITHMIC`;
p NULL or a gqr_parameter_t which will be filled with the data relevant to the selected rule type.
Returns
a gqr_t description of the rule in str, or an error code.
gqr_rule_name()
gchar * gqr_rule_name (gqr_t type)
Generate a string giving the name of the quadrature rule (Legendre, Hermite, etc.) and any singularities built into it.
Parameters
type a gqr_t describing a quadrature rule.
Returns
a string giving the name of rule type.
Referenced by gqr_rule_select().
gqr_rule_realloc()
 gqr_rule_t * gqr_rule_realloc (gqr_rule_t * g, gint n)
Reallocate memory for a Gaussian quadrature rule to allow for a change in rule length.
Parameters
g gqr_rule_t to reallocate;
n new maximum length of rule (number of abscissae and weights).
Returns
newly allocated rule.
References gqr_rule_alloc().
gqr_rule_scale()
gint gqr_rule_scale (gqr_rule_t * g, gdouble a, gdouble b, gdouble * xbar, gdouble * dx)
Set the scaling for a rule so that the integral is approximated by: $I\approx\Delta x \sum_{j=0}^{n}w_{j}f(x_{j})$ where $x=\bar{x}+\Delta x t_{j}$.
Parameters
g Gaussian quadrature rule;
a lower limit of integration;
b upper limit of integration;
xbar $\bar{x}$;
dx $\Delta x$.
Returns
0 on success.
Referenced by gqr_finite_part_integral(), and gqr_rule_bgr_check().
gqr_rule_select()
gint gqr_rule_select (gqr_rule_t * g, gqr_t type, gint n, gqr_parameter_t * p)
Fill a Gaussian quadrature rule with abscissae and weights of a chosen type.
You should exercise some caution in the Jacobi quadrature rules, since there are issues with calculating the nodes especially for weight function exponenents less than -1/2. You are advised to check the rule against a known solution, for example by checking that the sum of the weights correctly integrates the weighting function.
Parameters
g rule to fill;
type a gqr_t for the rule;
n number of points in rule;
p gqr_parameter_t of parameters for rule, or NULL for rules with no parameter (e.g. standard Legendre quadrature).
Returns
0 on success.
References gqr_rule_name(), and grule_bgr().
Referenced by gqr_rule_bgr_check(), and grule_bgr().
gqr_rule_write()
gint gqr_rule_write (gqr_rule_t * g, FILE * f)
Write the abscissae and weights of a Gaussian quadrature rule to a file.
Parameters
g Gaussian quadrature rule;
f file stream to write to.
Returns
0 on success.